services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-server
    volumes:
      - .:/var/www
    ports:
      - "80:80"
    depends_on:
      - db
    working_dir: /var/www/public
    command: php -S 0.0.0.0:80

  db:
    image: postgres:latest
    container_name: mydb
    restart: always
    environment:
      POSTGRES_DB: artisanat
      POSTGRES_USER: root
      POSTGRES_PASSWORD: test
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: root@gmail.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data:
